[module/bspwm]
type = internal/bspwm
format-font = 3

; Only show workspaces defined on the same output as the bar
; NOTE: The bspwm and XRandR monitor names must match, which they do by default.
; But if you rename your bspwm monitors with bspc -n this option will no longer
; behave correctly.
; Default: true
pin-workspaces = true

; Output mode flags after focused state label
; Default: false
inline-mode = false

; Create click handler used to focus workspace
; Default: true
enable-click = true

; Create scroll handlers used to cycle workspaces
; Default: true
enable-scroll = false

; Set the scroll cycle direction 
; Default: true
reverse-scroll = false

; Use fuzzy (partial) matching on labels when assigning 
; icons to workspaces
; Example: code;♚ will apply the icon to all workspaces 
; containing 'code' in the label
; Default: false
fuzzy-match = true

; Only scroll through occupied workspaces
; Default: false
; New in version 3.6.0
occupied-scroll = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;

; Available tags:
;   <label-monitor>
;   <label-state> - gets replaced with <label-(focused|urgent|occupied|empty)>
;   <label-mode> - gets replaced with <label-(monocle|tiled|fullscreen|floating|locked|sticky|private)>
; Default: <label-state>
format = <label-state> <label-mode>

; Available tokens:
;   %name%
; Default: %name%
label-monitor = %name%

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon% %name%
label-focused = %icon%

label-focused-foreground = ${colors.primary}
label-focused-overline = ${colors.primary}

#fba922

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon% %name%
label-occupied = %icon%
label-occupied-foreground = ${colors.foreground-alt}
#label-occupied-underline = ${colors.background}
#555555

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon% %name%
label-urgent = %icon%
label-urgent-foreground = ${colors.alert}
#label-urgent-background = #bd2c40
#label-urgent-underline = ${colors.alert}

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon% %name%
label-empty = %icon%
label-empty-foreground = #55

; The following labels will be used to indicate the layout/mode
; for the focused workspace. Requires <label-mode>
;
; Available tokens:
;   None
;label-monocle = M
;label-tiled = T
;label-fullscreen = f
;label-floating = F
;label-pseudotiled = P
;label-locked = 
;label-locked-foreground = #bd2c40
;label-sticky = 
;label-sticky-foreground = #fba922
;label-private = 
;label-private-foreground = #bd2c40
;label-marked = M

; Separator in between workspaces
label-separator = " "
label-separator-padding = 3pt
label-separator-foreground = ${colors.background}

[module/xwindow]
type = internal/xwindow
label-font = 4
label-active = %title:0:70:...%
label-maxlen = 95

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
format = <label-layout>
label-layout = %icon%
label-layout-foreground = ${colors.foreground}
layout-icon-0 = ru;%{F#FF4040}%{T4}RU%{T-}%{F-}
layout-icon-1 = us;%{F#00BFFF}%{T4}EN%{T-}%{F-}

[module/date]
type = internal/date
label-font = 1

interval = 1
date = %a, %d - %H:%M
date-alt = %d-%m-%Y %H:%M:%S
label-foreground = ${colors.foreground}
label = "%{A1:gsimplecal:}%date%%{A}"
#click-right = exec orage

[module/tray]
type = internal/tray
format-margin = 1px
tray-spacing = 10px
tray-foreground = ${colors.foreground}
tray-background = ${colors.background}