[module/memory]
type = internal/memory
#label-font = 3

interval = 2
#format-prefix = " "
#format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%
#label-warn = %percentage_swap_used%
label-foreground = ${colors.primary}

format = <ramp-used> %{F#00FF00}<ramp-swap-used>

# Memory circle, gradient blue-green-yellow-red
ramp-used-0 = %{F#8AB4F8}󰪞
ramp-used-1 = %{F#9C9EFB}󰪟
ramp-used-2 = %{F#B788FC}󰪠
ramp-used-3 = %{F#D86FFB}󰪡
ramp-used-4 = %{F#FB56F4}󰪢
ramp-used-5 = %{F#FC4ECA}󰪣
ramp-used-6 = %{F#FC50A2}󰪤
ramp-used-7 = %{F#F66D7C}󰪥

# Swap circle, lime color
ramp-swap-used-0 = 󰪞
ramp-swap-used-1 = 󰪟
ramp-swap-used-2 = 󰪠
ramp-swap-used-3 = 󰪡
ramp-swap-used-4 = 󰪢
ramp-swap-used-5 = 󰪣
ramp-swap-used-6 = 󰪤
ramp-swap-used-7 = 󰪥

[module/cpu]
type = internal/cpu
label-font = 5

interval = 2
#format-prefix = " "
#format-prefix-foreground = ${colors.primary}

#label = %percentage:2%%

format = <ramp-coreload>

ramp-coreload-spacing = 2pt
ramp-coreload-0 = %{F#00BFFF}▁
ramp-coreload-1 = %{F#00BFFF}▂
ramp-coreload-2 = %{F#55aa55}▃
ramp-coreload-3 = %{F#55aa55}▄
ramp-coreload-4 = %{F#FFFF00}▅
ramp-coreload-5 = %{F#FFFF00}▆
ramp-coreload-6 = %{F#FF4040}▇
ramp-coreload-7 = %{F#FF4040}█

[module/temperature]
type = internal/temperature
; Seconds to sleep between updates
; Default: 1
interval = 1

format = <ramp>

#format-prefix = " "
#format-prefix-foreground = ${colors.primary}
; Thermal zone to use
; To list all the zone types, run 
; $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 0
; Select thermal zone by name
; The name has to match the contents of /sys/class/thermal/thermal_zone*/type
; for the desired thermal zone.
; New in version 3.7.0
; Default: ""
zone-type = x86_pkg_temp
; Full path of temperature sysfs path
; Use `sensors` to find preferred temperature source, then run
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
; to find path to desired file
; Default reverts to thermal zone setting
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp1_input

; Base temperature for where to start the ramp (in degrees celsius)
; Default: 0
base-temperature = 45

; Threshold temperature to display warning label (in degrees celsius)
; Default: 80
warn-temperature = 70

label-warn = %{F#FF4040}

label-foreground = ${colors.primary}
label =  %temperature-c%

ramp-0 = %{F#00BFFF}
ramp-1 = %{F#FFFF00}

[module/filesystem]
type = internal/fs
label-font = 2
interval = 25
mount-0 = /
format-mounted = <label-mounted>
format-mounted-prefix = " "
format-mounted-prefix-foreground = ${colors.primary}
label-mounted = %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}