[module/weather]
type = custom/script
format-prefix = " "
label-foreground = ${colors.foreground}
exec = sh ~/.config/polybar/scripts/weather.sh
interval = 300
format-padding = 0

[module/redshift]
type = custom/script
exec = ~/.config/polybar/scripts/redshift.sh temperature 
click-left = ~/.config/polybar/scripts/redshift.sh toggle 
interval=2.0

[module/backlight]
type = custom/script
label-foreground = ${colors.primary}
exec = ~/.config/polybar/scripts/brightness.sh current
interval = 2
format-padding = 0

[module/powermenu]
type = custom/text
format = ""
format-background = ${colors.background}
format-foreground = ${colors.primary}
click-left = ~/.config/rofi/powermenu/type-2/powermenu.sh
#click-right = powermenu_t1

[module/openweathermap-fullfeatured]
type = custom/script
exec = ~/.config/polybar/scripts/openweathermap-fullfeatured.sh
interval = 600
label-font = 3

[module/jgmenu]
type = custom/text
content-padding = 1
content = ""
format-background = ${colors.background}
format-foreground = ${colors.primary}
format-font = 3
click-left = jgmenu_run > /dev/null 2>&1 &
