# Изменить размер дискового кеша и поведение подкачки.

vm.vfs_cache_pressure = 50
vm.swappiness = 180
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125
vm.page-cluster = 0

# Настраиваем управление выделением памяти
vm.overcommit_ratio = 100
vm.overcommit_memory = 1
vm.dirty_background_bytes = 4194304
vm.dirty_bytes = 4194304
vm.dirty_writeback_centisecs = 60000
vm.dirty_expire_centisecs = 60000
vm.dirty_ratio = 10
vm.dirty_background_ratio = 5
vm.laptop_mode = 0
